// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'ru'
	| 'sr'
	| 'uk'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​c​t​i​o​n
	 */
	ACTION: string
	/**
	 * A​d​d​ ​a​r​g​u​m​e​n​t
	 */
	ADD_ARGUMENT: string
	/**
	 * A​d​d​ ​n​e​w​ ​s​o​l​u​t​i​o​n
	 */
	ADD_NEW_SOLUTION: string
	/**
	 * A​r​g​u​m​e​n​t​s
	 */
	ARGUMENTS: string
	/**
	 * B​r​o​w​s​e
	 */
	BROWSE: string
	/**
	 * B​r​o​w​s​e​ ​P​r​o​j​e​c​t​s
	 */
	BROWSE_PROJECTS: string
	/**
	 * B​a​c​k
	 */
	BACK: string
	/**
	 * C​a​l​l​s​t​a​c​k
	 */
	CALLSTACK: string
	/**
	 * C​a​n​c​e​l
	 */
	CANCEL: string
	/**
	 * C​o​d​e
	 */
	CODE: string
	/**
	 * C​h​o​o​s​e​ ​l​o​c​a​l​e​.​.​.
	 */
	CHOOSE_LOCALE: string
	/**
	 * C​o​p​i​e​d​ ​c​o​d​e​ ​t​o​ ​c​l​i​p​b​o​a​r​d
	 */
	CODE_COPIED_TO_CLIPBOARD: string
	/**
	 * C​o​d​e​ ​R​u​n​n​e​r
	 */
	CODE_RUNNER: string
	/**
	 * C​o​n​s​o​l​e​ ​o​u​t​p​u​t
	 */
	CONSOLE_OUTPUT: string
	/**
	 * C​o​n​t​i​n​u​e
	 */
	CONTINUE: string
	/**
	 * C​o​p​y
	 */
	COPY: string
	/**
	 * C​o​p​y​ ​c​o​d​e​ ​t​o​ ​c​l​i​p​b​o​a​r​d
	 */
	COPY_CODE_TO_CLIPBOARD: string
	/**
	 * C​r​e​a​t​e​ ​n​e​w​ ​p​r​o​j​e​c​t
	 */
	CREATE_NEW_PROJECT: string
	/**
	 * C​u​r​r​e​n​t​ ​p​r​o​j​e​c​t
	 */
	CURRENT_PROJECT: string
	/**
	 * C​u​r​r​e​n​t​ ​u​s​e​r​ ​a​c​c​o​u​n​t
	 */
	CURRENT_USER_ACCOUNT: string
	/**
	 * D​a​r​k​ ​M​o​d​e
	 */
	DARK_MODE: string
	/**
	 * D​a​s​h​b​o​a​r​d
	 */
	DASHBOARD: string
	/**
	 * D​a​t​a​ ​S​t​r​u​c​t​u​r​e​s​ ​S​i​m​p​l​i​f​i​e​d
	 */
	DATA_STRUCTURES_SIMPLIFIED: string
	/**
	 * D​e​l​e​t​e
	 */
	DELETE: string
	/**
	 * D​e​l​e​t​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t
	 */
	DELETE_THIS_PROJECT: string
	/**
	 * D​e​l​e​t​e​ ​{​n​a​m​e​}​ ​a​r​g​u​m​e​n​t
	 * @param {string} name
	 */
	DELETE_X_ARGUMENT: RequiredParams<'name'>
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	DESCRIPTION: string
	/**
	 * D​S​t​r​u​c​t​ ​L​o​g​o
	 */
	DSTRUCT_LOGO: string
	/**
	 * E​d​i​t​ ​<​c​o​d​e​>​p​a​g​e​s​/​i​n​d​e​x​.​t​s​x​<​/​c​o​d​e​>​ ​a​n​d​ ​s​a​v​e​ ​t​o​ ​r​e​l​o​a​d​.
	 */
	EDIT_AND_SAVE: string
	/**
	 * E​d​i​t​ ​s​e​l​e​c​t​e​d​ ​p​r​o​j​e​c​t
	 */
	EDIT_SELECTED_PROJECT: string
	/**
	 * E​d​i​t​ ​s​o​l​u​t​i​o​n
	 */
	EDIT_SOLUTION: string
	/**
	 * E​d​i​t​ ​t​e​s​t​ ​c​a​s​e
	 */
	EDIT_TEST_CASE: string
	/**
	 * E​d​i​t​ ​t​h​e​ ​d​e​t​a​i​l​s​ ​o​f​ ​y​o​u​r​ ​t​e​s​t​ ​c​a​s​e​.
	 */
	EDIT_TEST_CASE_SUMMARY: string
	/**
	 * F​e​e​d​b​a​c​k
	 */
	FEEDBACK: string
	/**
	 * F​o​r​w​a​r​d
	 */
	FORWARD: string
	/**
	 * F​o​r​m​a​t​t​i​n​g​ ​i​c​o​n
	 */
	FORMATTING_ICON: string
	/**
	 * F​o​r​m​a​t​ ​c​o​d​e​ ​w​i​t​h
	 */
	FORMAT_CODE_WITH: string
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * I​n​p​u​t
	 */
	INPUT: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	LANGUAGE: string
	/**
	 * L​o​g​o​u​t
	 */
	LOGOUT: string
	/**
	 * M​a​i​n​ ​M​e​n​u
	 */
	MAIN_MENU: string
	/**
	 * m​s
	 */
	MS: string
	/**
	 * N​a​m​e
	 */
	NAME: string
	/**
	 * N​e​w
	 */
	NEW: string
	/**
	 * N​o​d​e
	 */
	NODE: string
	/**
	 * N​o​ ​d​a​t​a
	 */
	NO_DATA: string
	/**
	 * O​p​e​n​ ​o​p​t​i​o​n​s
	 */
	OPEN_OPTIONS: string
	/**
	 * O​u​t​p​u​t
	 */
	OUTPUT: string
	/**
	 * P​a​n​e​l​ ​t​a​b​s
	 */
	PANEL_TABS: string
	/**
	 * P​e​n​d​i​n​g​ ​c​h​a​n​g​e​s
	 */
	PENDING_CHANGES: string
	/**
	 * P​l​a​y​b​a​c​k​ ​i​n​t​e​r​v​a​l
	 */
	PLAYBACK_INTERVAL: string
	/**
	 * P​l​a​y​g​r​o​u​n​d
	 */
	PLAYGROUND: string
	/**
	 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​L​e​e​t​C​o​d​e​ ​a​c​c​o​u​n​t​ ​n​a​m​e​:
	 */
	PLEASE_ENTER_YOUR_LEETCODE_ACCOUNT_NAME: string
	/**
	 * P​r​o​f​i​l​e
	 */
	PROFILE: string
	/**
	 * P​r​o​j​e​c​t
	 */
	PROJECT: string
	/**
	 * P​r​o​j​e​c​t​ ​B​r​o​w​s​e​r
	 */
	PROJECT_BROWSER: string
	/**
	 * S​e​a​r​c​h​ ​p​r​o​j​e​c​t​s​ ​b​y​ ​t​i​t​l​e​.​.​.
	 */
	SEARCH_PROJECTS: string
	/**
	 * N​o​ ​p​r​o​j​e​c​t​s​ ​f​o​u​n​d
	 */
	NO_PROJECTS_FOUND: string
	/**
	 * N​o​ ​p​r​o​j​e​c​t​s​ ​m​a​t​c​h​ ​y​o​u​r​ ​f​i​l​t​e​r​s
	 */
	NO_PROJECTS_MATCH_FILTERS: string
	/**
	 * F​i​l​t​e​r​s
	 */
	FILTERS: string
	/**
	 * D​i​f​f​i​c​u​l​t​y
	 */
	FILTER_BY_DIFFICULTY: string
	/**
	 * S​h​o​w​ ​o​n​l​y​ ​n​e​w​ ​p​r​o​j​e​c​t​s
	 */
	SHOW_ONLY_NEW: string
	/**
	 * S​h​o​w​ ​o​n​l​y​ ​m​y​ ​p​r​o​j​e​c​t​s
	 */
	SHOW_ONLY_MINE: string
	/**
	 * C​l​e​a​r​ ​a​l​l​ ​f​i​l​t​e​r​s
	 */
	CLEAR_ALL_FILTERS: string
	/**
	 * S​o​r​t​ ​b​y
	 */
	SORT_BY: string
	/**
	 * T​i​t​l​e
	 */
	SORT_TITLE: string
	/**
	 * T​i​t​l​e​ ​(​A​-​Z​)
	 */
	SORT_TITLE_ASC: string
	/**
	 * T​i​t​l​e​ ​(​Z​-​A​)
	 */
	SORT_TITLE_DESC: string
	/**
	 * D​i​f​f​i​c​u​l​t​y
	 */
	SORT_DIFFICULTY: string
	/**
	 * D​i​f​f​i​c​u​l​t​y​ ​(​E​a​s​y​ ​→​ ​H​a​r​d​)
	 */
	SORT_DIFFICULTY_ASC: string
	/**
	 * D​i​f​f​i​c​u​l​t​y​ ​(​H​a​r​d​ ​→​ ​E​a​s​y​)
	 */
	SORT_DIFFICULTY_DESC: string
	/**
	 * D​a​t​e
	 */
	SORT_DATE: string
	/**
	 * D​a​t​e​ ​(​N​e​w​e​s​t​ ​F​i​r​s​t​)
	 */
	SORT_DATE_ASC: string
	/**
	 * D​a​t​e​ ​(​O​l​d​e​s​t​ ​F​i​r​s​t​)
	 */
	SORT_DATE_DESC: string
	/**
	 * C​a​t​e​g​o​r​y
	 */
	SORT_CATEGORY: string
	/**
	 * C​a​t​e​g​o​r​y​ ​(​A​-​Z​)
	 */
	SORT_CATEGORY_ASC: string
	/**
	 * C​a​t​e​g​o​r​y​ ​(​Z​-​A​)
	 */
	SORT_CATEGORY_DESC: string
	/**
	 * R​e​p​l​a​y
	 */
	REPLAY: string
	/**
	 * R​e​p​l​a​y​ ​p​r​e​v​i​o​u​s​ ​c​o​d​e​ ​r​e​s​u​l​t​ ​v​i​s​u​a​l​i​z​a​t​i​o​n
	 */
	REPLAY_PREVIOUS_CODE_RESULT_VISUALIZATION: string
	/**
	 * R​e​s​e​t
	 */
	RESET: string
	/**
	 * R​e​s​u​l​t​s
	 */
	RESULTS: string
	/**
	 * R​e​s​e​t​ ​d​a​t​a​ ​s​t​r​u​c​t​u​r​e​s​ ​t​o​ ​i​n​i​t​i​a​l​ ​s​t​a​t​e​s
	 */
	RESET_DATA_STRUCTURES: string
	/**
	 * R​e​t​r​y
	 */
	RETRY: string
	/**
	 * R​e​t​u​r​n​e​d
	 */
	RETURNED: string
	/**
	 * R​u​n
	 */
	RUN: string
	/**
	 * R​u​n​t​i​m​e
	 */
	RUNTIME: string
	/**
	 * R​u​n​ ​c​o​d​e
	 */
	RUN_CODE: string
	/**
	 * S​a​v​e​d​ ​t​o​ ​c​l​o​u​d
	 */
	SAVED_IN_THE_CLOUD: string
	/**
	 * S​e​l​e​c​t​e​d​ ​l​o​c​a​l​e​:
	 */
	SELECTED_LOCALE: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	SETTINGS: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	SIGN_IN: string
	/**
	 * S​i​g​n​-​i​n​ ​f​a​i​l​e​d
	 */
	SIGN_IN_FAILED: string
	/**
	 * S​i​g​n​ ​i​n​ ​t​o​ ​k​e​e​p​ ​t​r​a​c​k​ ​o​f​ ​y​o​u​r​ ​p​r​o​g​r​e​s​s​ ​a​n​d​ ​m​o​r​e​!
	 */
	SIGN_IN_TO_KEEP_TRACK_OF_YOUR_PROGRESS_AND_MORE: string
	/**
	 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​i​t​H​u​b​ ​o​r​ ​G​o​o​g​l​e​ ​i​n​ ​t​h​e​ ​t​o​p​ ​r​i​g​h​t​ ​c​o​r​n​e​r
	 */
	SIGN_IN_WITH_GITHUB_OR_GOOGLE_IN_THE_TOP_RIGHT: string
	/**
	 * S​l​u​g
	 */
	SLUG: string
	/**
	 * S​p​a​c​e​ ​C​o​m​p​l​e​x​i​t​y
	 */
	SPACE_COMPLEXITY: string
	/**
	 * S​u​b​m​i​t
	 */
	SUBMIT: string
	/**
	 * S​u​c​c​e​s​s
	 */
	SUCCESS: string
	/**
	 * S​y​n​c​i​n​g​ ​w​i​t​h​ ​s​e​r​v​e​r
	 */
	SYNCING_WITH_SERVER: string
	/**
	 * O​p​t​i​o​n​a​l​ ​t​e​s​t​ ​c​a​s​e​ ​d​e​s​c​r​i​p​t​i​o​n
	 */
	TEST_CASE_DESCRIPTION_HELPER_TEXT: string
	/**
	 * A​ ​s​h​o​r​t​ ​n​a​m​e​ ​f​o​r​ ​y​o​u​r​ ​t​e​s​t​ ​c​a​s​e
	 */
	TEST_CASE_NAME_HELPER_TEXT: string
	/**
	 * Y​o​u​ ​c​a​n​ ​e​d​i​t​ ​a​ ​s​l​u​g​ ​t​h​a​t​'​s​ ​u​s​e​d​ ​i​n​ ​t​h​e​ ​U​R​L​ ​t​o​ ​t​h​i​s​ ​t​e​s​t​ ​c​a​s​e
	 */
	TEST_CASE_SLUG_HELPER_TEXT: string
	/**
	 * T​i​m​e​s​t​a​m​p
	 */
	TIMESTAMP: string
	/**
	 * T​i​m​e​ ​C​o​m​p​l​e​x​i​t​y
	 */
	TIME_COMPLEXITY: string
	/**
	 * T​o​d​a​y​ ​i​s​ ​{​d​a​t​e​|​w​e​e​k​d​a​y​}
	 * @param {Date} date
	 */
	TODAY: RequiredParams<'date|weekday'>
	/**
	 * T​o​k​e​n
	 */
	TOKEN: string
	/**
	 * T​r​e​e​ ​V​i​e​w​e​r
	 */
	TREE_VIEWER: string
	/**
	 * T​r​y​ ​i​t​ ​o​u​t​ ​n​o​w
	 */
	TRY_IT_OUT_NOW: string
	/**
	 * T​y​p​e
	 */
	TYPE: string
	/**
	 * U​p​d​a​t​e
	 */
	UPDATE: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	USERNAME: string
	/**
	 * {​n​a​m​e​}​'​s​ ​D​a​s​h​b​o​a​r​d
	 * @param {string} name
	 */
	USER_DASHBOARD: RequiredParams<'name'>
	/**
	 * U​s​e​r​ ​S​e​t​t​i​n​g​s
	 */
	USER_SETTINGS: string
	/**
	 * V​i​s​u​a​l​i​z​e​ ​y​o​u​r​ ​L​e​e​t​C​o​d​e​ ​p​r​o​b​l​e​m​s​ ​j​u​s​t​ ​f​r​o​m​ ​y​o​u​r​ ​c​o​d​e
	 */
	VISUALIZE_YOUR_LEETCODE_PROBLEMS_JUST_FORM_YOUR_CODE: string
	/**
	 * Y​o​u​r​ ​c​h​a​n​g​e​s​ ​w​i​l​l​ ​b​e​ ​l​o​s​t
	 */
	YOUR_CHANGES_WILL_BE_LOST: string
	/**
	 * Y​o​u​r​ ​L​e​e​t​C​o​d​e​ ​a​c​c​o​u​n​t​ ​n​a​m​e​:
	 */
	YOUR_LEETCODE_ACCOUNT_NAME: string
	/**
	 * Y​o​u​r​ ​n​a​m​e​:
	 */
	YOUR_NAME: string
	/**
	 * Y​o​u​ ​d​o​n​'​t​ ​o​w​n​ ​t​h​i​s​ ​p​r​o​j​e​c​t
	 */
	YOU_DONT_OWN_THIS_PROJECT: string
	/**
	 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​b​e​ ​a​u​t​h​e​d​ ​t​o​ ​s​a​v​e​ ​c​o​d​e
	 */
	YOU_NEED_TO_BE_AUTHED_TO_SAVE_CODE: string
	/**
	 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​r​u​n​ ​t​h​e​ ​c​o​d​e​ ​f​i​r​s​t
	 */
	YOU_NEED_TO_RUN_THE_CODE_FIRST: string
}

export type TranslationFunctions = {
	/**
	 * Action
	 */
	ACTION: () => LocalizedString
	/**
	 * Add argument
	 */
	ADD_ARGUMENT: () => LocalizedString
	/**
	 * Add new solution
	 */
	ADD_NEW_SOLUTION: () => LocalizedString
	/**
	 * Arguments
	 */
	ARGUMENTS: () => LocalizedString
	/**
	 * Browse
	 */
	BROWSE: () => LocalizedString
	/**
	 * Browse Projects
	 */
	BROWSE_PROJECTS: () => LocalizedString
	/**
	 * Back
	 */
	BACK: () => LocalizedString
	/**
	 * Callstack
	 */
	CALLSTACK: () => LocalizedString
	/**
	 * Cancel
	 */
	CANCEL: () => LocalizedString
	/**
	 * Code
	 */
	CODE: () => LocalizedString
	/**
	 * Choose locale...
	 */
	CHOOSE_LOCALE: () => LocalizedString
	/**
	 * Copied code to clipboard
	 */
	CODE_COPIED_TO_CLIPBOARD: () => LocalizedString
	/**
	 * Code Runner
	 */
	CODE_RUNNER: () => LocalizedString
	/**
	 * Console output
	 */
	CONSOLE_OUTPUT: () => LocalizedString
	/**
	 * Continue
	 */
	CONTINUE: () => LocalizedString
	/**
	 * Copy
	 */
	COPY: () => LocalizedString
	/**
	 * Copy code to clipboard
	 */
	COPY_CODE_TO_CLIPBOARD: () => LocalizedString
	/**
	 * Create new project
	 */
	CREATE_NEW_PROJECT: () => LocalizedString
	/**
	 * Current project
	 */
	CURRENT_PROJECT: () => LocalizedString
	/**
	 * Current user account
	 */
	CURRENT_USER_ACCOUNT: () => LocalizedString
	/**
	 * Dark Mode
	 */
	DARK_MODE: () => LocalizedString
	/**
	 * Dashboard
	 */
	DASHBOARD: () => LocalizedString
	/**
	 * Data Structures Simplified
	 */
	DATA_STRUCTURES_SIMPLIFIED: () => LocalizedString
	/**
	 * Delete
	 */
	DELETE: () => LocalizedString
	/**
	 * Delete this project
	 */
	DELETE_THIS_PROJECT: () => LocalizedString
	/**
	 * Delete {name} argument
	 */
	DELETE_X_ARGUMENT: (arg: { name: string }) => LocalizedString
	/**
	 * Description
	 */
	DESCRIPTION: () => LocalizedString
	/**
	 * DStruct Logo
	 */
	DSTRUCT_LOGO: () => LocalizedString
	/**
	 * Edit <code>pages/index.tsx</code> and save to reload.
	 */
	EDIT_AND_SAVE: () => LocalizedString
	/**
	 * Edit selected project
	 */
	EDIT_SELECTED_PROJECT: () => LocalizedString
	/**
	 * Edit solution
	 */
	EDIT_SOLUTION: () => LocalizedString
	/**
	 * Edit test case
	 */
	EDIT_TEST_CASE: () => LocalizedString
	/**
	 * Edit the details of your test case.
	 */
	EDIT_TEST_CASE_SUMMARY: () => LocalizedString
	/**
	 * Feedback
	 */
	FEEDBACK: () => LocalizedString
	/**
	 * Forward
	 */
	FORWARD: () => LocalizedString
	/**
	 * Formatting icon
	 */
	FORMATTING_ICON: () => LocalizedString
	/**
	 * Format code with
	 */
	FORMAT_CODE_WITH: () => LocalizedString
	/**
	 * Hello {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Input
	 */
	INPUT: () => LocalizedString
	/**
	 * Language
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Logout
	 */
	LOGOUT: () => LocalizedString
	/**
	 * Main Menu
	 */
	MAIN_MENU: () => LocalizedString
	/**
	 * ms
	 */
	MS: () => LocalizedString
	/**
	 * Name
	 */
	NAME: () => LocalizedString
	/**
	 * New
	 */
	NEW: () => LocalizedString
	/**
	 * Node
	 */
	NODE: () => LocalizedString
	/**
	 * No data
	 */
	NO_DATA: () => LocalizedString
	/**
	 * Open options
	 */
	OPEN_OPTIONS: () => LocalizedString
	/**
	 * Output
	 */
	OUTPUT: () => LocalizedString
	/**
	 * Panel tabs
	 */
	PANEL_TABS: () => LocalizedString
	/**
	 * Pending changes
	 */
	PENDING_CHANGES: () => LocalizedString
	/**
	 * Playback interval
	 */
	PLAYBACK_INTERVAL: () => LocalizedString
	/**
	 * Playground
	 */
	PLAYGROUND: () => LocalizedString
	/**
	 * Please enter your LeetCode account name:
	 */
	PLEASE_ENTER_YOUR_LEETCODE_ACCOUNT_NAME: () => LocalizedString
	/**
	 * Profile
	 */
	PROFILE: () => LocalizedString
	/**
	 * Project
	 */
	PROJECT: () => LocalizedString
	/**
	 * Project Browser
	 */
	PROJECT_BROWSER: () => LocalizedString
	/**
	 * Search projects by title...
	 */
	SEARCH_PROJECTS: () => LocalizedString
	/**
	 * No projects found
	 */
	NO_PROJECTS_FOUND: () => LocalizedString
	/**
	 * No projects match your filters
	 */
	NO_PROJECTS_MATCH_FILTERS: () => LocalizedString
	/**
	 * Filters
	 */
	FILTERS: () => LocalizedString
	/**
	 * Difficulty
	 */
	FILTER_BY_DIFFICULTY: () => LocalizedString
	/**
	 * Show only new projects
	 */
	SHOW_ONLY_NEW: () => LocalizedString
	/**
	 * Show only my projects
	 */
	SHOW_ONLY_MINE: () => LocalizedString
	/**
	 * Clear all filters
	 */
	CLEAR_ALL_FILTERS: () => LocalizedString
	/**
	 * Sort by
	 */
	SORT_BY: () => LocalizedString
	/**
	 * Title
	 */
	SORT_TITLE: () => LocalizedString
	/**
	 * Title (A-Z)
	 */
	SORT_TITLE_ASC: () => LocalizedString
	/**
	 * Title (Z-A)
	 */
	SORT_TITLE_DESC: () => LocalizedString
	/**
	 * Difficulty
	 */
	SORT_DIFFICULTY: () => LocalizedString
	/**
	 * Difficulty (Easy → Hard)
	 */
	SORT_DIFFICULTY_ASC: () => LocalizedString
	/**
	 * Difficulty (Hard → Easy)
	 */
	SORT_DIFFICULTY_DESC: () => LocalizedString
	/**
	 * Date
	 */
	SORT_DATE: () => LocalizedString
	/**
	 * Date (Newest First)
	 */
	SORT_DATE_ASC: () => LocalizedString
	/**
	 * Date (Oldest First)
	 */
	SORT_DATE_DESC: () => LocalizedString
	/**
	 * Category
	 */
	SORT_CATEGORY: () => LocalizedString
	/**
	 * Category (A-Z)
	 */
	SORT_CATEGORY_ASC: () => LocalizedString
	/**
	 * Category (Z-A)
	 */
	SORT_CATEGORY_DESC: () => LocalizedString
	/**
	 * Replay
	 */
	REPLAY: () => LocalizedString
	/**
	 * Replay previous code result visualization
	 */
	REPLAY_PREVIOUS_CODE_RESULT_VISUALIZATION: () => LocalizedString
	/**
	 * Reset
	 */
	RESET: () => LocalizedString
	/**
	 * Results
	 */
	RESULTS: () => LocalizedString
	/**
	 * Reset data structures to initial states
	 */
	RESET_DATA_STRUCTURES: () => LocalizedString
	/**
	 * Retry
	 */
	RETRY: () => LocalizedString
	/**
	 * Returned
	 */
	RETURNED: () => LocalizedString
	/**
	 * Run
	 */
	RUN: () => LocalizedString
	/**
	 * Runtime
	 */
	RUNTIME: () => LocalizedString
	/**
	 * Run code
	 */
	RUN_CODE: () => LocalizedString
	/**
	 * Saved to cloud
	 */
	SAVED_IN_THE_CLOUD: () => LocalizedString
	/**
	 * Selected locale:
	 */
	SELECTED_LOCALE: () => LocalizedString
	/**
	 * Settings
	 */
	SETTINGS: () => LocalizedString
	/**
	 * Sign in
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Sign-in failed
	 */
	SIGN_IN_FAILED: () => LocalizedString
	/**
	 * Sign in to keep track of your progress and more!
	 */
	SIGN_IN_TO_KEEP_TRACK_OF_YOUR_PROGRESS_AND_MORE: () => LocalizedString
	/**
	 * Sign in with GitHub or Google in the top right corner
	 */
	SIGN_IN_WITH_GITHUB_OR_GOOGLE_IN_THE_TOP_RIGHT: () => LocalizedString
	/**
	 * Slug
	 */
	SLUG: () => LocalizedString
	/**
	 * Space Complexity
	 */
	SPACE_COMPLEXITY: () => LocalizedString
	/**
	 * Submit
	 */
	SUBMIT: () => LocalizedString
	/**
	 * Success
	 */
	SUCCESS: () => LocalizedString
	/**
	 * Syncing with server
	 */
	SYNCING_WITH_SERVER: () => LocalizedString
	/**
	 * Optional test case description
	 */
	TEST_CASE_DESCRIPTION_HELPER_TEXT: () => LocalizedString
	/**
	 * A short name for your test case
	 */
	TEST_CASE_NAME_HELPER_TEXT: () => LocalizedString
	/**
	 * You can edit a slug that's used in the URL to this test case
	 */
	TEST_CASE_SLUG_HELPER_TEXT: () => LocalizedString
	/**
	 * Timestamp
	 */
	TIMESTAMP: () => LocalizedString
	/**
	 * Time Complexity
	 */
	TIME_COMPLEXITY: () => LocalizedString
	/**
	 * Today is {date|weekday}
	 */
	TODAY: (arg: { date: Date }) => LocalizedString
	/**
	 * Token
	 */
	TOKEN: () => LocalizedString
	/**
	 * Tree Viewer
	 */
	TREE_VIEWER: () => LocalizedString
	/**
	 * Try it out now
	 */
	TRY_IT_OUT_NOW: () => LocalizedString
	/**
	 * Type
	 */
	TYPE: () => LocalizedString
	/**
	 * Update
	 */
	UPDATE: () => LocalizedString
	/**
	 * Username
	 */
	USERNAME: () => LocalizedString
	/**
	 * {name}'s Dashboard
	 */
	USER_DASHBOARD: (arg: { name: string }) => LocalizedString
	/**
	 * User Settings
	 */
	USER_SETTINGS: () => LocalizedString
	/**
	 * Visualize your LeetCode problems just from your code
	 */
	VISUALIZE_YOUR_LEETCODE_PROBLEMS_JUST_FORM_YOUR_CODE: () => LocalizedString
	/**
	 * Your changes will be lost
	 */
	YOUR_CHANGES_WILL_BE_LOST: () => LocalizedString
	/**
	 * Your LeetCode account name:
	 */
	YOUR_LEETCODE_ACCOUNT_NAME: () => LocalizedString
	/**
	 * Your name:
	 */
	YOUR_NAME: () => LocalizedString
	/**
	 * You don't own this project
	 */
	YOU_DONT_OWN_THIS_PROJECT: () => LocalizedString
	/**
	 * You need to be authed to save code
	 */
	YOU_NEED_TO_BE_AUTHED_TO_SAVE_CODE: () => LocalizedString
	/**
	 * You need to run the code first
	 */
	YOU_NEED_TO_RUN_THE_CODE_FIRST: () => LocalizedString
}

export type Formatters = {
	weekday: (value: Date) => unknown
}
