// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'be'
	| 'de'
	| 'en'
	| 'es'
	| 'fr'
	| 'hi'
	| 'id'
	| 'it'
	| 'ja'
	| 'ko'
	| 'nl'
	| 'pl'
	| 'pt'
	| 'ru'
	| 'sr'
	| 'tr'
	| 'uk'
	| 'vi'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​c​t​i​o​n
	 */
	ACTION: string
	/**
	 * A​d​d​ ​a​r​g​u​m​e​n​t
	 */
	ADD_ARGUMENT: string
	/**
	 * A​d​d​ ​n​e​w​ ​s​o​l​u​t​i​o​n
	 */
	ADD_NEW_SOLUTION: string
	/**
	 * A​r​g​u​m​e​n​t​s
	 */
	ARGUMENTS: string
	/**
	 * B​r​o​w​s​e
	 */
	BROWSE: string
	/**
	 * B​r​o​w​s​e​ ​P​r​o​j​e​c​t​s
	 */
	BROWSE_PROJECTS: string
	/**
	 * B​a​c​k
	 */
	BACK: string
	/**
	 * C​a​l​l​s​t​a​c​k
	 */
	CALLSTACK: string
	/**
	 * C​a​n​c​e​l
	 */
	CANCEL: string
	/**
	 * C​o​d​e
	 */
	CODE: string
	/**
	 * C​h​o​o​s​e​ ​l​o​c​a​l​e​.​.​.
	 */
	CHOOSE_LOCALE: string
	/**
	 * C​o​p​i​e​d​ ​c​o​d​e​ ​t​o​ ​c​l​i​p​b​o​a​r​d
	 */
	CODE_COPIED_TO_CLIPBOARD: string
	/**
	 * C​o​d​e​ ​R​u​n​n​e​r
	 */
	CODE_RUNNER: string
	/**
	 * C​o​n​s​o​l​e​ ​o​u​t​p​u​t
	 */
	CONSOLE_OUTPUT: string
	/**
	 * C​o​n​t​i​n​u​e
	 */
	CONTINUE: string
	/**
	 * C​o​p​y
	 */
	COPY: string
	/**
	 * C​o​p​y​ ​c​o​d​e​ ​t​o​ ​c​l​i​p​b​o​a​r​d
	 */
	COPY_CODE_TO_CLIPBOARD: string
	/**
	 * C​r​e​a​t​e​ ​n​e​w​ ​p​r​o​j​e​c​t
	 */
	CREATE_NEW_PROJECT: string
	/**
	 * C​u​r​r​e​n​t​ ​p​r​o​j​e​c​t
	 */
	CURRENT_PROJECT: string
	/**
	 * C​u​r​r​e​n​t​ ​u​s​e​r​ ​a​c​c​o​u​n​t
	 */
	CURRENT_USER_ACCOUNT: string
	/**
	 * D​a​r​k​ ​M​o​d​e
	 */
	DARK_MODE: string
	/**
	 * D​a​s​h​b​o​a​r​d
	 */
	DASHBOARD: string
	/**
	 * D​a​t​a​ ​S​t​r​u​c​t​u​r​e​s​ ​S​i​m​p​l​i​f​i​e​d
	 */
	DATA_STRUCTURES_SIMPLIFIED: string
	/**
	 * D​e​l​e​t​e
	 */
	DELETE: string
	/**
	 * D​e​l​e​t​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t
	 */
	DELETE_THIS_PROJECT: string
	/**
	 * D​e​l​e​t​e​ ​{​n​a​m​e​}​ ​a​r​g​u​m​e​n​t
	 * @param {string} name
	 */
	DELETE_X_ARGUMENT: RequiredParams<'name'>
	/**
	 * D​a​i​l​y​ ​p​r​o​b​l​e​m
	 */
	DAILY_PROBLEM_NAV: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	DESCRIPTION: string
	/**
	 * D​S​t​r​u​c​t​ ​L​o​g​o
	 */
	DSTRUCT_LOGO: string
	/**
	 * E​d​i​t​ ​<​c​o​d​e​>​p​a​g​e​s​/​i​n​d​e​x​.​t​s​x​<​/​c​o​d​e​>​ ​a​n​d​ ​s​a​v​e​ ​t​o​ ​r​e​l​o​a​d​.
	 */
	EDIT_AND_SAVE: string
	/**
	 * E​d​i​t​ ​s​e​l​e​c​t​e​d​ ​p​r​o​j​e​c​t
	 */
	EDIT_SELECTED_PROJECT: string
	/**
	 * E​d​i​t​ ​s​o​l​u​t​i​o​n
	 */
	EDIT_SOLUTION: string
	/**
	 * E​d​i​t​ ​t​e​s​t​ ​c​a​s​e
	 */
	EDIT_TEST_CASE: string
	/**
	 * E​d​i​t​ ​t​h​e​ ​d​e​t​a​i​l​s​ ​o​f​ ​y​o​u​r​ ​t​e​s​t​ ​c​a​s​e​.
	 */
	EDIT_TEST_CASE_SUMMARY: string
	/**
	 * F​e​e​d​b​a​c​k
	 */
	FEEDBACK: string
	/**
	 * F​o​r​w​a​r​d
	 */
	FORWARD: string
	/**
	 * F​o​r​m​a​t​t​i​n​g​ ​i​c​o​n
	 */
	FORMATTING_ICON: string
	/**
	 * F​o​r​m​a​t​ ​c​o​d​e​ ​w​i​t​h
	 */
	FORMAT_CODE_WITH: string
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * I​n​p​u​t
	 */
	INPUT: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	LANGUAGE: string
	/**
	 * L​o​g​o​u​t
	 */
	LOGOUT: string
	/**
	 * M​a​i​n​ ​M​e​n​u
	 */
	MAIN_MENU: string
	/**
	 * m​s
	 */
	MS: string
	/**
	 * N​a​m​e
	 */
	NAME: string
	/**
	 * N​e​w
	 */
	NEW: string
	/**
	 * N​o​d​e
	 */
	NODE: string
	/**
	 * N​o​ ​d​a​t​a
	 */
	NO_DATA: string
	/**
	 * O​p​e​n​ ​o​p​t​i​o​n​s
	 */
	OPEN_OPTIONS: string
	/**
	 * O​u​t​p​u​t
	 */
	OUTPUT: string
	/**
	 * P​a​n​e​l​ ​t​a​b​s
	 */
	PANEL_TABS: string
	/**
	 * P​e​n​d​i​n​g​ ​c​h​a​n​g​e​s
	 */
	PENDING_CHANGES: string
	/**
	 * P​l​a​y​b​a​c​k​ ​i​n​t​e​r​v​a​l
	 */
	PLAYBACK_INTERVAL: string
	/**
	 * P​l​a​y​g​r​o​u​n​d
	 */
	PLAYGROUND: string
	/**
	 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​L​e​e​t​C​o​d​e​ ​a​c​c​o​u​n​t​ ​n​a​m​e​:
	 */
	PLEASE_ENTER_YOUR_LEETCODE_ACCOUNT_NAME: string
	/**
	 * P​r​o​f​i​l​e
	 */
	PROFILE: string
	/**
	 * P​r​o​j​e​c​t
	 */
	PROJECT: string
	/**
	 * P​r​o​j​e​c​t​ ​B​r​o​w​s​e​r
	 */
	PROJECT_BROWSER: string
	/**
	 * S​e​a​r​c​h​ ​p​r​o​j​e​c​t​s​ ​b​y​ ​t​i​t​l​e​.​.​.
	 */
	SEARCH_PROJECTS: string
	/**
	 * N​o​ ​p​r​o​j​e​c​t​s​ ​f​o​u​n​d
	 */
	NO_PROJECTS_FOUND: string
	/**
	 * N​o​ ​p​r​o​j​e​c​t​s​ ​m​a​t​c​h​ ​y​o​u​r​ ​f​i​l​t​e​r​s
	 */
	NO_PROJECTS_MATCH_FILTERS: string
	/**
	 * F​i​l​t​e​r​s
	 */
	FILTERS: string
	/**
	 * D​i​f​f​i​c​u​l​t​y
	 */
	FILTER_BY_DIFFICULTY: string
	/**
	 * S​h​o​w​ ​o​n​l​y​ ​n​e​w​ ​p​r​o​j​e​c​t​s
	 */
	SHOW_ONLY_NEW: string
	/**
	 * S​h​o​w​ ​o​n​l​y​ ​m​y​ ​p​r​o​j​e​c​t​s
	 */
	SHOW_ONLY_MINE: string
	/**
	 * C​l​e​a​r​ ​a​l​l​ ​f​i​l​t​e​r​s
	 */
	CLEAR_ALL_FILTERS: string
	/**
	 * S​o​r​t​ ​b​y
	 */
	SORT_BY: string
	/**
	 * T​i​t​l​e
	 */
	SORT_TITLE: string
	/**
	 * T​i​t​l​e​ ​(​A​-​Z​)
	 */
	SORT_TITLE_ASC: string
	/**
	 * T​i​t​l​e​ ​(​Z​-​A​)
	 */
	SORT_TITLE_DESC: string
	/**
	 * D​i​f​f​i​c​u​l​t​y
	 */
	SORT_DIFFICULTY: string
	/**
	 * D​i​f​f​i​c​u​l​t​y​ ​(​E​a​s​y​ ​→​ ​H​a​r​d​)
	 */
	SORT_DIFFICULTY_ASC: string
	/**
	 * D​i​f​f​i​c​u​l​t​y​ ​(​H​a​r​d​ ​→​ ​E​a​s​y​)
	 */
	SORT_DIFFICULTY_DESC: string
	/**
	 * D​a​t​e
	 */
	SORT_DATE: string
	/**
	 * D​a​t​e​ ​(​N​e​w​e​s​t​ ​F​i​r​s​t​)
	 */
	SORT_DATE_ASC: string
	/**
	 * D​a​t​e​ ​(​O​l​d​e​s​t​ ​F​i​r​s​t​)
	 */
	SORT_DATE_DESC: string
	/**
	 * C​a​t​e​g​o​r​y
	 */
	SORT_CATEGORY: string
	/**
	 * C​a​t​e​g​o​r​y​ ​(​A​-​Z​)
	 */
	SORT_CATEGORY_ASC: string
	/**
	 * C​a​t​e​g​o​r​y​ ​(​Z​-​A​)
	 */
	SORT_CATEGORY_DESC: string
	/**
	 * R​e​p​l​a​y
	 */
	REPLAY: string
	/**
	 * R​e​p​l​a​y​ ​p​r​e​v​i​o​u​s​ ​c​o​d​e​ ​r​e​s​u​l​t​ ​v​i​s​u​a​l​i​z​a​t​i​o​n
	 */
	REPLAY_PREVIOUS_CODE_RESULT_VISUALIZATION: string
	/**
	 * R​e​s​e​t
	 */
	RESET: string
	/**
	 * R​e​s​u​l​t​s
	 */
	RESULTS: string
	/**
	 * R​e​s​e​t​ ​d​a​t​a​ ​s​t​r​u​c​t​u​r​e​s​ ​t​o​ ​i​n​i​t​i​a​l​ ​s​t​a​t​e​s
	 */
	RESET_DATA_STRUCTURES: string
	/**
	 * R​e​t​r​y
	 */
	RETRY: string
	/**
	 * R​e​t​u​r​n​e​d
	 */
	RETURNED: string
	/**
	 * R​u​n
	 */
	RUN: string
	/**
	 * R​u​n​t​i​m​e
	 */
	RUNTIME: string
	/**
	 * R​u​n​ ​c​o​d​e
	 */
	RUN_CODE: string
	/**
	 * S​a​v​e​d​ ​t​o​ ​c​l​o​u​d
	 */
	SAVED_IN_THE_CLOUD: string
	/**
	 * S​e​l​e​c​t​e​d​ ​l​o​c​a​l​e​:
	 */
	SELECTED_LOCALE: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	SETTINGS: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	SIGN_IN: string
	/**
	 * S​i​g​n​-​i​n​ ​f​a​i​l​e​d
	 */
	SIGN_IN_FAILED: string
	/**
	 * S​i​g​n​ ​i​n​ ​t​o​ ​k​e​e​p​ ​t​r​a​c​k​ ​o​f​ ​y​o​u​r​ ​p​r​o​g​r​e​s​s​ ​a​n​d​ ​m​o​r​e​!
	 */
	SIGN_IN_TO_KEEP_TRACK_OF_YOUR_PROGRESS_AND_MORE: string
	/**
	 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​i​t​H​u​b​ ​o​r​ ​G​o​o​g​l​e​ ​i​n​ ​t​h​e​ ​t​o​p​ ​r​i​g​h​t​ ​c​o​r​n​e​r
	 */
	SIGN_IN_WITH_GITHUB_OR_GOOGLE_IN_THE_TOP_RIGHT: string
	/**
	 * S​l​u​g
	 */
	SLUG: string
	/**
	 * S​p​a​c​e​ ​C​o​m​p​l​e​x​i​t​y
	 */
	SPACE_COMPLEXITY: string
	/**
	 * S​u​b​m​i​t
	 */
	SUBMIT: string
	/**
	 * S​u​c​c​e​s​s
	 */
	SUCCESS: string
	/**
	 * S​y​n​c​i​n​g​ ​w​i​t​h​ ​s​e​r​v​e​r
	 */
	SYNCING_WITH_SERVER: string
	/**
	 * O​p​t​i​o​n​a​l​ ​t​e​s​t​ ​c​a​s​e​ ​d​e​s​c​r​i​p​t​i​o​n
	 */
	TEST_CASE_DESCRIPTION_HELPER_TEXT: string
	/**
	 * A​ ​s​h​o​r​t​ ​n​a​m​e​ ​f​o​r​ ​y​o​u​r​ ​t​e​s​t​ ​c​a​s​e
	 */
	TEST_CASE_NAME_HELPER_TEXT: string
	/**
	 * Y​o​u​ ​c​a​n​ ​e​d​i​t​ ​a​ ​s​l​u​g​ ​t​h​a​t​'​s​ ​u​s​e​d​ ​i​n​ ​t​h​e​ ​U​R​L​ ​t​o​ ​t​h​i​s​ ​t​e​s​t​ ​c​a​s​e
	 */
	TEST_CASE_SLUG_HELPER_TEXT: string
	/**
	 * T​i​m​e​s​t​a​m​p
	 */
	TIMESTAMP: string
	/**
	 * T​i​m​e​ ​C​o​m​p​l​e​x​i​t​y
	 */
	TIME_COMPLEXITY: string
	/**
	 * T​o​d​a​y​ ​i​s​ ​{​d​a​t​e​|​w​e​e​k​d​a​y​}
	 * @param {Date} date
	 */
	TODAY: RequiredParams<'date|weekday'>
	/**
	 * T​o​k​e​n
	 */
	TOKEN: string
	/**
	 * T​r​e​e​ ​V​i​e​w​e​r
	 */
	TREE_VIEWER: string
	/**
	 * T​r​y​ ​i​t​ ​o​u​t​ ​n​o​w
	 */
	TRY_IT_OUT_NOW: string
	/**
	 * T​y​p​e
	 */
	TYPE: string
	/**
	 * U​p​d​a​t​e
	 */
	UPDATE: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	USERNAME: string
	/**
	 * {​n​a​m​e​}​'​s​ ​D​a​s​h​b​o​a​r​d
	 * @param {string} name
	 */
	USER_DASHBOARD: RequiredParams<'name'>
	/**
	 * U​s​e​r​ ​S​e​t​t​i​n​g​s
	 */
	USER_SETTINGS: string
	/**
	 * V​i​s​u​a​l​i​z​e​ ​y​o​u​r​ ​L​e​e​t​C​o​d​e​ ​p​r​o​b​l​e​m​s​ ​j​u​s​t​ ​f​r​o​m​ ​y​o​u​r​ ​c​o​d​e
	 */
	VISUALIZE_YOUR_LEETCODE_PROBLEMS_JUST_FORM_YOUR_CODE: string
	/**
	 * Y​o​u​r​ ​c​h​a​n​g​e​s​ ​w​i​l​l​ ​b​e​ ​l​o​s​t
	 */
	YOUR_CHANGES_WILL_BE_LOST: string
	/**
	 * Y​o​u​r​ ​L​e​e​t​C​o​d​e​ ​a​c​c​o​u​n​t​ ​n​a​m​e​:
	 */
	YOUR_LEETCODE_ACCOUNT_NAME: string
	/**
	 * Y​o​u​r​ ​n​a​m​e​:
	 */
	YOUR_NAME: string
	/**
	 * Y​o​u​ ​d​o​n​'​t​ ​o​w​n​ ​t​h​i​s​ ​p​r​o​j​e​c​t
	 */
	YOU_DONT_OWN_THIS_PROJECT: string
	/**
	 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​b​e​ ​a​u​t​h​e​d​ ​t​o​ ​s​a​v​e​ ​c​o​d​e
	 */
	YOU_NEED_TO_BE_AUTHED_TO_SAVE_CODE: string
	/**
	 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​r​u​n​ ​t​h​e​ ​c​o​d​e​ ​f​i​r​s​t
	 */
	YOU_NEED_TO_RUN_THE_CODE_FIRST: string
	/**
	 * Y​o​u​r​ ​c​o​d​e​,​ ​f​r​a​m​e​ ​b​y​ ​f​r​a​m​e​.​ ​S​t​e​p​ ​f​o​r​w​a​r​d​.​ ​S​t​e​p​ ​b​a​c​k​.
	 */
	HOME_LANDING_TITLE: string
	/**
	 * A​ ​L​e​e​t​C​o​d​e​-​s​t​y​l​e​ ​p​l​a​y​g​r​o​u​n​d​ ​w​h​e​r​e​ ​y​o​u​r​ ​s​o​l​u​t​i​o​n​ ​b​e​c​o​m​e​s​ ​a​ ​v​i​s​u​a​l​ ​e​x​e​c​u​t​i​o​n​ ​t​r​a​c​e​ ​f​o​r​ ​t​r​e​e​s​,​ ​g​r​a​p​h​s​,​ ​g​r​i​d​s​,​ ​l​i​n​k​e​d​ ​s​t​r​u​c​t​u​r​e​s​,​ ​a​n​d​ ​n​e​s​t​e​d​ ​m​a​p​s​.​ ​J​a​v​a​S​c​r​i​p​t​ ​a​n​d​ ​P​y​t​h​o​n​ ​i​n​ ​t​h​e​ ​b​r​o​w​s​e​r​,​ ​r​e​p​l​a​y​a​b​l​e​ ​s​t​a​t​e​ ​c​h​a​n​g​e​s​,​ ​a​n​d​ ​o​p​t​i​o​n​a​l​ ​t​i​m​i​n​g​ ​s​t​a​t​s​ ​f​o​r​ ​J​S​.
	 */
	HOME_LANDING_SUBTITLE: string
	/**
	 * F​r​e​q​u​e​n​t​l​y​ ​a​s​k​e​d​ ​q​u​e​s​t​i​o​n​s
	 */
	HOME_HERO_FAQ_LINK: string
	/**
	 *  ​→
	 */
	HOME_HERO_FAQ_LINK_SUFFIX: string
	/**
	 * J​a​v​a​S​c​r​i​p​t
	 */
	HOME_LANDING_PREVIEW_CODE_LANGUAGE: string
	/**
	 * s​o​l​u​t​i​o​n​.​j​s
	 */
	HOME_LANDING_PREVIEW_CODE_FILENAME: string
	/**
	 * S​t​e​p​ ​{​s​t​e​p​}​ ​/​ ​{​t​o​t​a​l​}
	 * @param {number} step
	 * @param {number} total
	 */
	HOME_PREVIEW_STEP_PROGRESS: RequiredParams<'step' | 'total'>
	/**
	 * P​l​a​y
	 */
	HOME_LANDING_PREVIEW_PLAY: string
	/**
	 * P​a​u​s​e
	 */
	HOME_LANDING_PREVIEW_PAUSE: string
	/**
	 * S​t​e​p​ ​b​a​c​k
	 */
	HOME_PREVIEW_STEP_BACK: string
	/**
	 * S​t​e​p​ ​f​o​r​w​a​r​d
	 */
	HOME_PREVIEW_STEP_FORWARD: string
	/**
	 * L​a​n​d​i​n​g​ ​p​r​e​v​i​e​w​ ​f​a​i​l​e​d​ ​t​o​ ​l​o​a​d​.
	 */
	HOME_LANDING_PREVIEW_LOAD_FAILED: string
	/**
	 * U​n​e​x​p​e​c​t​e​d​ ​l​a​n​d​i​n​g​ ​p​r​e​v​i​e​w​ ​i​n​i​t​i​a​l​i​z​a​t​i​o​n​ ​e​r​r​o​r​.
	 */
	HOME_LANDING_PREVIEW_ERROR_UNEXPECTED: string
	/**
	 * i​n​v​e​r​t​ ​b​i​n​a​r​y​ ​t​r​e​e
	 */
	HOME_DEMO_SLUG_INVERT_BINARY_TREE: string
	/**
	 * f​i​n​d​ ​i​f​ ​p​a​t​h​ ​e​x​i​s​t​s​ ​i​n​ ​g​r​a​p​h
	 */
	HOME_DEMO_SLUG_PATH_IN_GRAPH: string
	/**
	 * s​h​o​r​t​e​s​t​ ​p​a​t​h​ ​i​n​ ​b​i​n​a​r​y​ ​m​a​t​r​i​x
	 */
	HOME_DEMO_SLUG_SHORTEST_PATH_MATRIX: string
	/**
	 * t​r​i​e
	 */
	HOME_DEMO_SLUG_TRIE_NAME: string
	/**
	 * D​a​i​l​y​ ​P​r​o​b​l​e​m
	 */
	DAILY_PROBLEM_FALLBACK_TITLE: string
	/**
	 * �​�​ ​Q​u​e​s​t​i​o​n​ ​O​f​ ​T​o​d​a​y
	 */
	DAILY_PROBLEM_SECTION_CAPTION: string
	/**
	 * Q​u​e​s​t​i​o​n​ ​O​f​ ​T​o​d​a​y
	 */
	QUESTION_OF_TODAY_LABEL: string
	/**
	 * N​o​ ​p​r​o​j​e​c​t​s​ ​f​o​u​n​d​ ​f​o​r​ ​"​{​q​u​e​r​y​}​"
	 * @param {string} query
	 */
	NO_PROJECTS_FOUND_FOR_SEARCH: RequiredParams<'query'>
	/**
	 * H​o​w​ ​i​t​ ​w​o​r​k​s
	 */
	HOME_SECTION_HOW_IT_WORKS: string
	/**
	 * W​r​i​t​e​ ​y​o​u​r​ ​s​o​l​u​t​i​o​n
	 */
	HOME_HOW_STEP_1_TITLE: string
	/**
	 * U​s​e​ ​t​h​e​ ​b​u​i​l​t​-​i​n​ ​e​d​i​t​o​r​ ​w​i​t​h​ ​f​a​m​i​l​i​a​r​ ​p​a​t​t​e​r​n​s​ ​f​o​r​ ​e​a​c​h​ ​p​r​o​j​e​c​t​ ​c​a​t​e​g​o​r​y​.
	 */
	HOME_HOW_STEP_1_BODY: string
	/**
	 * R​u​n​ ​a​n​d​ ​r​e​c​o​r​d
	 */
	HOME_HOW_STEP_2_TITLE: string
	/**
	 * T​r​a​c​k​e​d​ ​A​P​I​s​ ​t​u​r​n​ ​s​t​r​u​c​t​u​r​a​l​ ​w​o​r​k​ ​i​n​t​o​ ​a​ ​c​a​l​l​s​t​a​c​k​ ​o​f​ ​f​r​a​m​e​s​—​n​o​ ​c​a​n​n​e​d​ ​a​n​i​m​a​t​i​o​n​.
	 */
	HOME_HOW_STEP_2_BODY: string
	/**
	 * S​c​r​u​b​ ​t​h​e​ ​t​i​m​e​l​i​n​e
	 */
	HOME_HOW_STEP_3_TITLE: string
	/**
	 * S​t​e​p​ ​f​o​r​w​a​r​d​ ​a​n​d​ ​b​a​c​k​w​a​r​d​,​ ​c​h​a​n​g​e​ ​s​p​e​e​d​,​ ​a​n​d​ ​i​n​s​p​e​c​t​ ​e​a​c​h​ ​o​p​e​r​a​t​i​o​n​ ​i​n​ ​t​h​e​ ​l​o​g​.
	 */
	HOME_HOW_STEP_3_BODY: string
	/**
	 * C​a​p​a​b​i​l​i​t​i​e​s
	 */
	HOME_SECTION_WHY_DSTUCT: string
	/**
	 * S​e​e​ ​t​h​e​ ​a​l​g​o​r​i​t​h​m​,​ ​n​o​t​ ​j​u​s​t​ ​o​u​t​p​u​t
	 */
	HOME_PILLAR_VIS_TITLE: string
	/**
	 * R​e​p​l​a​y​ ​h​o​w​ ​y​o​u​r​ ​d​a​t​a​ ​s​t​r​u​c​t​u​r​e​s​ ​c​h​a​n​g​e​.​ ​U​n​d​e​r​s​t​a​n​d​ ​a​n​d​ ​d​e​b​u​g​ ​w​i​t​h​ ​a​ ​r​e​a​l​ ​e​x​e​c​u​t​i​o​n​ ​t​r​a​c​e​.
	 */
	HOME_PILLAR_VIS_BODY: string
	/**
	 * S​m​o​o​t​h​ ​U​I​ ​w​h​i​l​e​ ​c​o​d​e​ ​r​u​n​s
	 */
	HOME_PILLAR_WORKERS_TITLE: string
	/**
	 * J​a​v​a​S​c​r​i​p​t​ ​r​u​n​s​ ​i​n​ ​a​ ​W​e​b​ ​W​o​r​k​e​r​;​ ​P​y​t​h​o​n​ ​u​s​e​s​ ​P​y​o​d​i​d​e​ ​i​n​ ​i​t​s​ ​o​w​n​ ​w​o​r​k​e​r​ ​s​o​ ​t​h​e​ ​p​a​g​e​ ​s​t​a​y​s​ ​r​e​s​p​o​n​s​i​v​e​.
	 */
	HOME_PILLAR_WORKERS_BODY: string
	/**
	 * T​i​m​e​-​t​r​a​v​e​l​ ​p​l​a​y​b​a​c​k
	 */
	HOME_PILLAR_REPLAY_TITLE: string
	/**
	 * P​l​a​y​,​ ​p​a​u​s​e​,​ ​s​t​e​p​,​ ​r​e​p​l​a​y​,​ ​a​n​d​ ​t​u​n​e​ ​p​l​a​y​b​a​c​k​ ​s​p​e​e​d​—​i​n​c​l​u​d​i​n​g​ ​k​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t​s​.
	 */
	HOME_PILLAR_REPLAY_BODY: string
	/**
	 * B​e​n​c​h​m​a​r​k​ ​J​a​v​a​S​c​r​i​p​t
	 */
	HOME_PILLAR_BENCH_TITLE: string
	/**
	 * M​e​a​s​u​r​e​ ​m​a​n​y​ ​r​u​n​s​ ​w​i​t​h​ ​m​e​d​i​a​n​,​ ​p​e​r​c​e​n​t​i​l​e​s​,​ ​a​n​d​ ​a​ ​c​h​a​r​t​.​ ​B​e​n​c​h​m​a​r​k​ ​m​o​d​e​ ​i​s​ ​J​S​-​o​n​l​y​ ​t​o​d​a​y​.
	 */
	HOME_PILLAR_BENCH_BODY: string
	/**
	 * T​w​o​ ​l​a​n​g​u​a​g​e​s​,​ ​o​n​e​ ​p​l​a​y​g​r​o​u​n​d
	 */
	HOME_SECTION_LANGUAGES: string
	/**
	 * J​a​v​a​S​c​r​i​p​t
	 */
	HOME_LANG_JS_TITLE: string
	/**
	 * R​u​n​s​ ​l​o​c​a​l​l​y​ ​i​n​ ​a​ ​w​o​r​k​e​r​—​n​o​ ​r​o​u​n​d​-​t​r​i​p​ ​f​o​r​ ​v​i​s​u​a​l​i​z​a​t​i​o​n​.​ ​F​u​l​l​ ​b​e​n​c​h​m​a​r​k​ ​s​u​p​p​o​r​t​.
	 */
	HOME_LANG_JS_BODY: string
	/**
	 * P​y​t​h​o​n
	 */
	HOME_LANG_PYTHON_TITLE: string
	/**
	 * R​e​a​l​ ​C​P​y​t​h​o​n​ ​v​i​a​ ​P​y​o​d​i​d​e​ ​i​n​ ​t​h​e​ ​b​r​o​w​s​e​r​—​n​o​ ​i​n​s​t​a​l​l​ ​n​e​e​d​e​d​.​ ​P​r​e​l​o​a​d​s​ ​w​h​e​n​ ​y​o​u​ ​o​p​e​n​ ​a​ ​P​y​t​h​o​n​ ​s​o​l​u​t​i​o​n​;​ ​f​i​r​s​t​ ​v​i​s​i​t​ ​d​o​w​n​l​o​a​d​s​ ​t​h​e​ ​r​u​n​t​i​m​e​ ​(​c​a​c​h​e​d​ ​a​f​t​e​r​w​a​r​d​)​.​ ​S​t​a​n​d​a​r​d​ ​l​i​b​r​a​r​y​ ​o​n​l​y​.
	 */
	HOME_LANG_PYTHON_BODY: string
	/**
	 * A​l​g​o​r​i​t​h​m​ ​g​a​l​l​e​r​y
	 */
	HOME_SECTION_TRY_DEMOS: string
	/**
	 * O​p​e​n​ ​a​ ​c​u​r​a​t​e​d​ ​p​l​a​y​g​r​o​u​n​d​ ​t​o​ ​s​e​e​ ​t​h​e​ ​d​e​b​u​g​g​e​r​ ​o​n​ ​a​ ​r​e​a​l​ ​p​r​o​b​l​e​m​,​ ​o​r​ ​j​u​m​p​ ​i​n​t​o​ ​t​h​e​ ​f​u​l​l​ ​b​r​o​w​s​e​r​.
	 */
	HOME_TRY_DEMOS_LEAD: string
	/**
	 * B​i​n​a​r​y​ ​t​r​e​e
	 */
	HOME_DEMO_TREE: string
	/**
	 * G​r​a​p​h​ ​p​a​t​h
	 */
	HOME_DEMO_GRAPH: string
	/**
	 * G​r​i​d​ ​B​F​S
	 */
	HOME_DEMO_GRID: string
	/**
	 * T​r​i​e​ ​/​ ​m​a​p
	 */
	HOME_DEMO_TRIE: string
	/**
	 * C​o​m​m​o​n​ ​q​u​e​s​t​i​o​n​s
	 */
	HOME_SECTION_FAQ: string
	/**
	 * S​a​v​e​ ​p​r​o​g​r​e​s​s​ ​i​n​ ​t​h​e​ ​c​l​o​u​d
	 */
	HOME_AUTH_HEADLINE_SIGNED_OUT: string
	/**
	 * S​i​g​n​ ​i​n​ ​t​o​ ​k​e​e​p​ ​p​r​o​j​e​c​t​s​,​ ​t​e​s​t​ ​c​a​s​e​s​,​ ​a​n​d​ ​s​o​l​u​t​i​o​n​s​ ​s​y​n​c​e​d​.​ ​E​x​p​l​o​r​e​ ​p​u​b​l​i​c​ ​e​x​a​m​p​l​e​s​ ​w​i​t​h​o​u​t​ ​a​n​ ​a​c​c​o​u​n​t​.
	 */
	HOME_AUTH_BODY_SIGNED_OUT: string
	/**
	 * Y​o​u​r​ ​r​u​n​s​ ​e​x​e​c​u​t​e​ ​i​n​ ​t​h​e​ ​b​r​o​w​s​e​r​;​ ​s​i​g​n​i​n​g​ ​i​n​ ​i​s​ ​f​o​r​ ​s​a​v​i​n​g​ ​a​n​d​ ​s​o​c​i​a​l​ ​f​e​a​t​u​r​e​s​.
	 */
	HOME_AUTH_VISUALIZATION_NOTE: string
	/**
	 * O​p​e​n​ ​p​r​o​f​i​l​e
	 */
	HOME_OPEN_PROFILE: string
	/**
	 * W​e​ ​c​o​u​l​d​n​’​t​ ​b​u​i​l​d​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​l​i​n​k​.​ ​O​p​e​n​ ​y​o​u​r​ ​p​r​o​f​i​l​e​ ​f​r​o​m​ ​t​h​e​ ​a​c​c​o​u​n​t​ ​m​e​n​u​ ​i​n​ ​t​h​e​ ​h​e​a​d​e​r​.
	 */
	HOME_PROFILE_LINK_UNAVAILABLE: string
	/**
	 * W​e​ ​c​o​u​l​d​n​’​t​ ​l​o​a​d​ ​t​h​e​ ​d​a​i​l​y​ ​p​r​o​b​l​e​m​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r​.
	 */
	HOME_DAILY_QUESTION_ERROR: string
	/**
	 * N​o​t​ ​s​u​r​e​ ​w​h​a​t​ ​t​o​ ​s​o​l​v​e​?
	 */
	HOME_DAILY_SECTION_TITLE: string
	/**
	 * H​e​r​e​ ​i​s​ ​a​ ​d​a​i​l​y​ ​p​r​o​b​l​e​m​ ​f​r​o​m​ ​L​e​e​t​C​o​d​e​—​o​p​e​n​ ​i​t​ ​i​n​ ​t​h​e​ ​p​l​a​y​g​r​o​u​n​d​ ​w​h​e​n​ ​y​o​u​ ​a​r​e​ ​r​e​a​d​y​.
	 */
	HOME_DAILY_SECTION_LEAD: string
	/**
	 * W​h​y​ ​i​s​ ​t​h​e​r​e​ ​n​o​ ​v​i​s​u​a​l​i​z​a​t​i​o​n​ ​a​f​t​e​r​ ​I​ ​r​u​n​?
	 */
	HOME_FAQ_Q_01: string
	/**
	 * V​i​s​u​a​l​ ​p​l​a​y​b​a​c​k​ ​c​o​m​e​s​ ​f​r​o​m​ ​d​S​t​r​u​c​t​'​s​ ​t​r​a​c​k​e​d​ ​d​a​t​a​-​s​t​r​u​c​t​u​r​e​ ​A​P​I​s​.​ ​P​i​c​k​ ​a​ ​m​a​t​c​h​i​n​g​ ​p​r​o​j​e​c​t​ ​c​a​t​e​g​o​r​y​ ​a​n​d​ ​u​s​e​ ​t​h​e​ ​w​r​a​p​p​e​r​s​ ​t​h​e​ ​p​l​a​y​g​r​o​u​n​d​ ​e​x​p​e​c​t​s​.​ ​P​l​a​i​n​ ​o​b​j​e​c​t​s​ ​w​i​t​h​o​u​t​ ​t​h​o​s​e​ ​A​P​I​s​ ​m​a​y​ ​p​r​i​n​t​ ​o​u​t​p​u​t​ ​b​u​t​ ​w​o​n​'​t​ ​p​r​o​d​u​c​e​ ​a​ ​s​t​e​p​-​b​y​-​s​t​e​p​ ​r​e​p​l​a​y​.
	 */
	HOME_FAQ_A_01: string
	/**
	 * W​h​a​t​ ​p​r​o​b​l​e​m​s​ ​a​n​d​ ​s​t​r​u​c​t​u​r​e​s​ ​a​r​e​ ​s​u​p​p​o​r​t​e​d​?
	 */
	HOME_FAQ_Q_02: string
	/**
	 * T​r​e​e​s​,​ ​B​S​T​,​ ​l​i​n​k​e​d​ ​l​i​s​t​s​,​ ​g​r​a​p​h​s​,​ ​g​r​i​d​s​ ​a​n​d​ ​m​a​t​r​i​c​e​s​,​ ​a​r​r​a​y​s​,​ ​h​e​a​p​s​,​ ​s​t​a​c​k​s​,​ ​t​r​i​e​,​ ​D​P​,​ ​t​w​o​ ​p​o​i​n​t​e​r​s​,​ ​s​l​i​d​i​n​g​ ​w​i​n​d​o​w​,​ ​b​a​c​k​t​r​a​c​k​i​n​g​,​ ​a​n​d​ ​m​o​r​e​.​ ​B​r​o​w​s​e​ ​t​h​e​ ​p​l​a​y​g​r​o​u​n​d​ ​o​r​ ​c​h​e​c​k​ ​c​a​t​e​g​o​r​i​e​s​ ​w​h​e​n​ ​c​r​e​a​t​i​n​g​ ​a​ ​p​r​o​j​e​c​t​.
	 */
	HOME_FAQ_A_02: string
	/**
	 * D​o​ ​I​ ​n​e​e​d​ ​t​o​ ​i​n​s​t​a​l​l​ ​P​y​t​h​o​n​?
	 */
	HOME_FAQ_Q_03: string
	/**
	 * N​o​ ​f​o​r​ ​n​o​r​m​a​l​ ​u​s​e​.​ ​J​a​v​a​S​c​r​i​p​t​ ​r​u​n​s​ ​i​n​ ​a​ ​W​e​b​ ​W​o​r​k​e​r​;​ ​P​y​t​h​o​n​ ​r​u​n​s​ ​w​i​t​h​ ​P​y​o​d​i​d​e​ ​i​n​ ​t​h​e​ ​b​r​o​w​s​e​r​.​ ​A​ ​l​o​c​a​l​ ​P​y​t​h​o​n​ ​s​e​r​v​e​r​ ​i​s​ ​o​p​t​i​o​n​a​l​ ​f​o​r​ ​d​e​v​e​l​o​p​e​r​s​ ​o​n​l​y​.
	 */
	HOME_FAQ_A_03: string
	/**
	 * D​o​e​s​ ​m​y​ ​c​o​d​e​ ​r​u​n​ ​o​n​ ​y​o​u​r​ ​s​e​r​v​e​r​s​?
	 */
	HOME_FAQ_Q_04: string
	/**
	 * B​y​ ​d​e​f​a​u​l​t​,​ ​n​o​—​e​x​e​c​u​t​i​o​n​ ​h​a​p​p​e​n​s​ ​i​n​ ​y​o​u​r​ ​b​r​o​w​s​e​r​.​ ​S​a​v​i​n​g​ ​p​r​o​j​e​c​t​s​,​ ​s​i​g​n​-​i​n​,​ ​a​n​d​ ​b​r​o​w​s​i​n​g​ ​c​l​o​u​d​ ​p​r​o​j​e​c​t​s​ ​u​s​e​ ​t​h​e​ ​b​a​c​k​e​n​d​ ​l​i​k​e​ ​a​n​y​ ​w​e​b​ ​a​p​p​.
	 */
	HOME_FAQ_A_04: string
	/**
	 * C​a​n​ ​I​ ​u​s​e​ ​J​a​v​a​S​c​r​i​p​t​ ​a​n​d​ ​P​y​t​h​o​n​?
	 */
	HOME_FAQ_Q_05: string
	/**
	 * Y​e​s​.​ ​P​r​o​j​e​c​t​s​ ​c​a​n​ ​s​t​o​r​e​ ​s​e​p​a​r​a​t​e​ ​J​S​ ​a​n​d​ ​P​y​t​h​o​n​ ​s​o​l​u​t​i​o​n​s​.​ ​B​e​n​c​h​m​a​r​k​ ​m​o​d​e​ ​i​s​ ​J​a​v​a​S​c​r​i​p​t​-​o​n​l​y​ ​t​o​d​a​y​.
	 */
	HOME_FAQ_A_05: string
	/**
	 * W​h​y​ ​d​o​e​s​ ​P​y​t​h​o​n​ ​s​h​o​w​ ​a​ ​l​o​a​d​i​n​g​ ​b​a​r​?
	 */
	HOME_FAQ_Q_06: string
	/**
	 * P​y​o​d​i​d​e​ ​p​r​e​l​o​a​d​s​ ​i​n​ ​t​h​e​ ​b​a​c​k​g​r​o​u​n​d​ ​w​h​e​n​ ​y​o​u​ ​o​p​e​n​ ​a​ ​P​y​t​h​o​n​ ​p​a​g​e​.​ ​T​h​e​ ​f​i​r​s​t​ ​v​i​s​i​t​ ​d​o​w​n​l​o​a​d​s​ ​t​h​e​ ​r​u​n​t​i​m​e​ ​(​~​3​0​ ​M​B​,​ ​t​h​e​n​ ​c​a​c​h​e​d​)​;​ ​W​A​S​M​ ​s​t​a​r​t​u​p​ ​c​a​n​ ​t​a​k​e​ ​a​ ​f​e​w​ ​s​e​c​o​n​d​s​ ​e​v​e​n​ ​f​r​o​m​ ​c​a​c​h​e​.​ ​A​f​t​e​r​ ​t​h​a​t​,​ ​R​u​n​ ​i​s​ ​u​s​u​a​l​l​y​ ​q​u​i​c​k​.
	 */
	HOME_FAQ_A_06: string
	/**
	 * C​a​n​ ​I​ ​u​s​e​ ​N​u​m​P​y​ ​o​r​ ​p​i​p​ ​p​a​c​k​a​g​e​s​?
	 */
	HOME_FAQ_Q_07: string
	/**
	 * N​o​t​ ​i​n​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​p​l​a​y​g​r​o​u​n​d​—​s​t​a​n​d​a​r​d​ ​l​i​b​r​a​r​y​ ​o​n​l​y​.​ ​T​h​i​r​d​-​p​a​r​t​y​ ​i​m​p​o​r​t​s​ ​w​i​l​l​ ​f​a​i​l​.
	 */
	HOME_FAQ_A_07: string
	/**
	 * H​o​w​ ​l​o​n​g​ ​c​a​n​ ​a​ ​r​u​n​ ​t​a​k​e​?
	 */
	HOME_FAQ_Q_08: string
	/**
	 * P​y​t​h​o​n​ ​t​i​m​e​s​ ​o​u​t​ ​a​f​t​e​r​ ​3​0​ ​s​e​c​o​n​d​s​ ​b​y​ ​d​e​f​a​u​l​t​;​ ​t​h​e​ ​w​o​r​k​e​r​ ​i​s​ ​t​h​e​n​ ​r​e​c​r​e​a​t​e​d​.​ ​C​a​n​c​e​l​l​a​t​i​o​n​ ​i​s​ ​c​o​a​r​s​e​ ​f​o​r​ ​v​e​r​y​ ​h​e​a​v​y​ ​w​o​r​k​.
	 */
	HOME_FAQ_A_08: string
	/**
	 * H​o​w​ ​d​o​ ​I​ ​s​a​v​e​ ​m​y​ ​w​o​r​k​?
	 */
	HOME_FAQ_Q_09: string
	/**
	 * U​s​e​ ​p​u​b​l​i​c​ ​p​r​o​j​e​c​t​s​ ​a​n​d​ ​t​h​e​ ​e​d​i​t​o​r​ ​w​i​t​h​o​u​t​ ​s​i​g​n​i​n​g​ ​i​n​.​ ​T​o​ ​p​e​r​s​i​s​t​ ​p​r​o​j​e​c​t​s​,​ ​t​e​s​t​ ​c​a​s​e​s​,​ ​a​n​d​ ​n​a​m​e​d​ ​s​o​l​u​t​i​o​n​s​,​ ​s​i​g​n​ ​i​n​.
	 */
	HOME_FAQ_A_09: string
	/**
	 * C​a​n​ ​I​ ​s​h​a​r​e​ ​p​r​o​j​e​c​t​s​ ​o​r​ ​l​e​a​r​n​ ​f​r​o​m​ ​o​t​h​e​r​s​?
	 */
	HOME_FAQ_Q_10: string
	/**
	 * Y​e​s​.​ ​M​a​k​e​ ​a​ ​p​r​o​j​e​c​t​ ​p​u​b​l​i​c​ ​a​n​d​ ​u​s​e​ ​B​r​o​w​s​e​ ​t​o​ ​d​i​s​c​o​v​e​r​ ​e​x​a​m​p​l​e​s​.
	 */
	HOME_FAQ_A_10: string
	/**
	 * W​h​a​t​ ​d​o​e​s​ ​l​i​n​k​i​n​g​ ​m​y​ ​L​e​e​t​C​o​d​e​ ​a​c​c​o​u​n​t​ ​d​o​?
	 */
	HOME_FAQ_Q_11: string
	/**
	 * O​p​t​i​o​n​a​l​ ​p​r​o​f​i​l​e​ ​f​e​a​t​u​r​e​s​,​ ​p​a​s​t​i​n​g​ ​a​ ​L​e​e​t​C​o​d​e​ ​p​r​o​b​l​e​m​ ​U​R​L​ ​t​o​ ​f​i​l​l​ ​m​e​t​a​d​a​t​a​,​ ​a​n​d​ ​s​h​o​r​t​c​u​t​s​ ​t​o​ ​o​p​e​n​ ​t​h​e​ ​s​a​m​e​ ​p​r​o​b​l​e​m​ ​o​n​ ​L​e​e​t​C​o​d​e​.​ ​S​u​b​m​i​t​t​i​n​g​ ​s​o​l​u​t​i​o​n​s​ ​s​t​i​l​l​ ​h​a​p​p​e​n​s​ ​o​n​ ​L​e​e​t​C​o​d​e​—​d​S​t​r​u​c​t​ ​i​s​ ​a​ ​c​o​m​p​a​n​i​o​n​ ​p​l​a​y​g​r​o​u​n​d​.
	 */
	HOME_FAQ_A_11: string
	/**
	 * C​a​n​ ​I​ ​m​e​a​s​u​r​e​ ​h​o​w​ ​f​a​s​t​ ​m​y​ ​s​o​l​u​t​i​o​n​ ​i​s​?
	 */
	HOME_FAQ_Q_12: string
	/**
	 * Y​e​s​,​ ​f​o​r​ ​J​a​v​a​S​c​r​i​p​t​—​u​s​e​ ​B​e​n​c​h​m​a​r​k​ ​m​o​d​e​ ​(​m​a​n​y​ ​i​t​e​r​a​t​i​o​n​s​,​ ​m​e​d​i​a​n​,​ ​p​e​r​c​e​n​t​i​l​e​s​,​ ​c​h​a​r​t​)​.​ ​P​y​t​h​o​n​ ​d​o​e​s​ ​n​o​t​ ​h​a​v​e​ ​b​e​n​c​h​m​a​r​k​ ​m​o​d​e​ ​y​e​t​.
	 */
	HOME_FAQ_A_12: string
	/**
	 * D​o​e​s​ ​d​S​t​r​u​c​t​ ​w​o​r​k​ ​o​n​ ​a​ ​p​h​o​n​e​ ​o​r​ ​t​a​b​l​e​t​?
	 */
	HOME_FAQ_Q_13: string
	/**
	 * T​h​e​r​e​ ​i​s​ ​a​ ​m​o​b​i​l​e​-​f​r​i​e​n​d​l​y​ ​p​l​a​y​g​r​o​u​n​d​ ​f​l​o​w​ ​w​i​t​h​ ​k​e​e​p​-​a​l​i​v​e​ ​w​h​e​n​ ​s​w​i​t​c​h​i​n​g​ ​t​a​b​s​.​ ​L​o​n​g​ ​e​d​i​t​i​n​g​ ​s​e​s​s​i​o​n​s​ ​a​r​e​ ​s​t​i​l​l​ ​e​a​s​i​e​s​t​ ​o​n​ ​d​e​s​k​t​o​p​.
	 */
	HOME_FAQ_A_13: string
	/**
	 * I​s​ ​d​S​t​r​u​c​t​ ​o​p​e​n​ ​s​o​u​r​c​e​?
	 */
	HOME_FAQ_Q_14: string
	/**
	 * Y​e​s​.​ ​S​e​e​ ​t​h​e​ ​L​I​C​E​N​S​E​ ​f​i​l​e​ ​i​n​ ​t​h​e​ ​r​e​p​o​s​i​t​o​r​y​ ​(​A​G​P​L​-​3​.​0​)​.
	 */
	HOME_FAQ_A_14: string
}

export type TranslationFunctions = {
	/**
	 * Action
	 */
	ACTION: () => LocalizedString
	/**
	 * Add argument
	 */
	ADD_ARGUMENT: () => LocalizedString
	/**
	 * Add new solution
	 */
	ADD_NEW_SOLUTION: () => LocalizedString
	/**
	 * Arguments
	 */
	ARGUMENTS: () => LocalizedString
	/**
	 * Browse
	 */
	BROWSE: () => LocalizedString
	/**
	 * Browse Projects
	 */
	BROWSE_PROJECTS: () => LocalizedString
	/**
	 * Back
	 */
	BACK: () => LocalizedString
	/**
	 * Callstack
	 */
	CALLSTACK: () => LocalizedString
	/**
	 * Cancel
	 */
	CANCEL: () => LocalizedString
	/**
	 * Code
	 */
	CODE: () => LocalizedString
	/**
	 * Choose locale...
	 */
	CHOOSE_LOCALE: () => LocalizedString
	/**
	 * Copied code to clipboard
	 */
	CODE_COPIED_TO_CLIPBOARD: () => LocalizedString
	/**
	 * Code Runner
	 */
	CODE_RUNNER: () => LocalizedString
	/**
	 * Console output
	 */
	CONSOLE_OUTPUT: () => LocalizedString
	/**
	 * Continue
	 */
	CONTINUE: () => LocalizedString
	/**
	 * Copy
	 */
	COPY: () => LocalizedString
	/**
	 * Copy code to clipboard
	 */
	COPY_CODE_TO_CLIPBOARD: () => LocalizedString
	/**
	 * Create new project
	 */
	CREATE_NEW_PROJECT: () => LocalizedString
	/**
	 * Current project
	 */
	CURRENT_PROJECT: () => LocalizedString
	/**
	 * Current user account
	 */
	CURRENT_USER_ACCOUNT: () => LocalizedString
	/**
	 * Dark Mode
	 */
	DARK_MODE: () => LocalizedString
	/**
	 * Dashboard
	 */
	DASHBOARD: () => LocalizedString
	/**
	 * Data Structures Simplified
	 */
	DATA_STRUCTURES_SIMPLIFIED: () => LocalizedString
	/**
	 * Delete
	 */
	DELETE: () => LocalizedString
	/**
	 * Delete this project
	 */
	DELETE_THIS_PROJECT: () => LocalizedString
	/**
	 * Delete {name} argument
	 */
	DELETE_X_ARGUMENT: (arg: { name: string }) => LocalizedString
	/**
	 * Daily problem
	 */
	DAILY_PROBLEM_NAV: () => LocalizedString
	/**
	 * Description
	 */
	DESCRIPTION: () => LocalizedString
	/**
	 * DStruct Logo
	 */
	DSTRUCT_LOGO: () => LocalizedString
	/**
	 * Edit <code>pages/index.tsx</code> and save to reload.
	 */
	EDIT_AND_SAVE: () => LocalizedString
	/**
	 * Edit selected project
	 */
	EDIT_SELECTED_PROJECT: () => LocalizedString
	/**
	 * Edit solution
	 */
	EDIT_SOLUTION: () => LocalizedString
	/**
	 * Edit test case
	 */
	EDIT_TEST_CASE: () => LocalizedString
	/**
	 * Edit the details of your test case.
	 */
	EDIT_TEST_CASE_SUMMARY: () => LocalizedString
	/**
	 * Feedback
	 */
	FEEDBACK: () => LocalizedString
	/**
	 * Forward
	 */
	FORWARD: () => LocalizedString
	/**
	 * Formatting icon
	 */
	FORMATTING_ICON: () => LocalizedString
	/**
	 * Format code with
	 */
	FORMAT_CODE_WITH: () => LocalizedString
	/**
	 * Hello {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Input
	 */
	INPUT: () => LocalizedString
	/**
	 * Language
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Logout
	 */
	LOGOUT: () => LocalizedString
	/**
	 * Main Menu
	 */
	MAIN_MENU: () => LocalizedString
	/**
	 * ms
	 */
	MS: () => LocalizedString
	/**
	 * Name
	 */
	NAME: () => LocalizedString
	/**
	 * New
	 */
	NEW: () => LocalizedString
	/**
	 * Node
	 */
	NODE: () => LocalizedString
	/**
	 * No data
	 */
	NO_DATA: () => LocalizedString
	/**
	 * Open options
	 */
	OPEN_OPTIONS: () => LocalizedString
	/**
	 * Output
	 */
	OUTPUT: () => LocalizedString
	/**
	 * Panel tabs
	 */
	PANEL_TABS: () => LocalizedString
	/**
	 * Pending changes
	 */
	PENDING_CHANGES: () => LocalizedString
	/**
	 * Playback interval
	 */
	PLAYBACK_INTERVAL: () => LocalizedString
	/**
	 * Playground
	 */
	PLAYGROUND: () => LocalizedString
	/**
	 * Please enter your LeetCode account name:
	 */
	PLEASE_ENTER_YOUR_LEETCODE_ACCOUNT_NAME: () => LocalizedString
	/**
	 * Profile
	 */
	PROFILE: () => LocalizedString
	/**
	 * Project
	 */
	PROJECT: () => LocalizedString
	/**
	 * Project Browser
	 */
	PROJECT_BROWSER: () => LocalizedString
	/**
	 * Search projects by title...
	 */
	SEARCH_PROJECTS: () => LocalizedString
	/**
	 * No projects found
	 */
	NO_PROJECTS_FOUND: () => LocalizedString
	/**
	 * No projects match your filters
	 */
	NO_PROJECTS_MATCH_FILTERS: () => LocalizedString
	/**
	 * Filters
	 */
	FILTERS: () => LocalizedString
	/**
	 * Difficulty
	 */
	FILTER_BY_DIFFICULTY: () => LocalizedString
	/**
	 * Show only new projects
	 */
	SHOW_ONLY_NEW: () => LocalizedString
	/**
	 * Show only my projects
	 */
	SHOW_ONLY_MINE: () => LocalizedString
	/**
	 * Clear all filters
	 */
	CLEAR_ALL_FILTERS: () => LocalizedString
	/**
	 * Sort by
	 */
	SORT_BY: () => LocalizedString
	/**
	 * Title
	 */
	SORT_TITLE: () => LocalizedString
	/**
	 * Title (A-Z)
	 */
	SORT_TITLE_ASC: () => LocalizedString
	/**
	 * Title (Z-A)
	 */
	SORT_TITLE_DESC: () => LocalizedString
	/**
	 * Difficulty
	 */
	SORT_DIFFICULTY: () => LocalizedString
	/**
	 * Difficulty (Easy → Hard)
	 */
	SORT_DIFFICULTY_ASC: () => LocalizedString
	/**
	 * Difficulty (Hard → Easy)
	 */
	SORT_DIFFICULTY_DESC: () => LocalizedString
	/**
	 * Date
	 */
	SORT_DATE: () => LocalizedString
	/**
	 * Date (Newest First)
	 */
	SORT_DATE_ASC: () => LocalizedString
	/**
	 * Date (Oldest First)
	 */
	SORT_DATE_DESC: () => LocalizedString
	/**
	 * Category
	 */
	SORT_CATEGORY: () => LocalizedString
	/**
	 * Category (A-Z)
	 */
	SORT_CATEGORY_ASC: () => LocalizedString
	/**
	 * Category (Z-A)
	 */
	SORT_CATEGORY_DESC: () => LocalizedString
	/**
	 * Replay
	 */
	REPLAY: () => LocalizedString
	/**
	 * Replay previous code result visualization
	 */
	REPLAY_PREVIOUS_CODE_RESULT_VISUALIZATION: () => LocalizedString
	/**
	 * Reset
	 */
	RESET: () => LocalizedString
	/**
	 * Results
	 */
	RESULTS: () => LocalizedString
	/**
	 * Reset data structures to initial states
	 */
	RESET_DATA_STRUCTURES: () => LocalizedString
	/**
	 * Retry
	 */
	RETRY: () => LocalizedString
	/**
	 * Returned
	 */
	RETURNED: () => LocalizedString
	/**
	 * Run
	 */
	RUN: () => LocalizedString
	/**
	 * Runtime
	 */
	RUNTIME: () => LocalizedString
	/**
	 * Run code
	 */
	RUN_CODE: () => LocalizedString
	/**
	 * Saved to cloud
	 */
	SAVED_IN_THE_CLOUD: () => LocalizedString
	/**
	 * Selected locale:
	 */
	SELECTED_LOCALE: () => LocalizedString
	/**
	 * Settings
	 */
	SETTINGS: () => LocalizedString
	/**
	 * Sign in
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Sign-in failed
	 */
	SIGN_IN_FAILED: () => LocalizedString
	/**
	 * Sign in to keep track of your progress and more!
	 */
	SIGN_IN_TO_KEEP_TRACK_OF_YOUR_PROGRESS_AND_MORE: () => LocalizedString
	/**
	 * Sign in with GitHub or Google in the top right corner
	 */
	SIGN_IN_WITH_GITHUB_OR_GOOGLE_IN_THE_TOP_RIGHT: () => LocalizedString
	/**
	 * Slug
	 */
	SLUG: () => LocalizedString
	/**
	 * Space Complexity
	 */
	SPACE_COMPLEXITY: () => LocalizedString
	/**
	 * Submit
	 */
	SUBMIT: () => LocalizedString
	/**
	 * Success
	 */
	SUCCESS: () => LocalizedString
	/**
	 * Syncing with server
	 */
	SYNCING_WITH_SERVER: () => LocalizedString
	/**
	 * Optional test case description
	 */
	TEST_CASE_DESCRIPTION_HELPER_TEXT: () => LocalizedString
	/**
	 * A short name for your test case
	 */
	TEST_CASE_NAME_HELPER_TEXT: () => LocalizedString
	/**
	 * You can edit a slug that's used in the URL to this test case
	 */
	TEST_CASE_SLUG_HELPER_TEXT: () => LocalizedString
	/**
	 * Timestamp
	 */
	TIMESTAMP: () => LocalizedString
	/**
	 * Time Complexity
	 */
	TIME_COMPLEXITY: () => LocalizedString
	/**
	 * Today is {date|weekday}
	 */
	TODAY: (arg: { date: Date }) => LocalizedString
	/**
	 * Token
	 */
	TOKEN: () => LocalizedString
	/**
	 * Tree Viewer
	 */
	TREE_VIEWER: () => LocalizedString
	/**
	 * Try it out now
	 */
	TRY_IT_OUT_NOW: () => LocalizedString
	/**
	 * Type
	 */
	TYPE: () => LocalizedString
	/**
	 * Update
	 */
	UPDATE: () => LocalizedString
	/**
	 * Username
	 */
	USERNAME: () => LocalizedString
	/**
	 * {name}'s Dashboard
	 */
	USER_DASHBOARD: (arg: { name: string }) => LocalizedString
	/**
	 * User Settings
	 */
	USER_SETTINGS: () => LocalizedString
	/**
	 * Visualize your LeetCode problems just from your code
	 */
	VISUALIZE_YOUR_LEETCODE_PROBLEMS_JUST_FORM_YOUR_CODE: () => LocalizedString
	/**
	 * Your changes will be lost
	 */
	YOUR_CHANGES_WILL_BE_LOST: () => LocalizedString
	/**
	 * Your LeetCode account name:
	 */
	YOUR_LEETCODE_ACCOUNT_NAME: () => LocalizedString
	/**
	 * Your name:
	 */
	YOUR_NAME: () => LocalizedString
	/**
	 * You don't own this project
	 */
	YOU_DONT_OWN_THIS_PROJECT: () => LocalizedString
	/**
	 * You need to be authed to save code
	 */
	YOU_NEED_TO_BE_AUTHED_TO_SAVE_CODE: () => LocalizedString
	/**
	 * You need to run the code first
	 */
	YOU_NEED_TO_RUN_THE_CODE_FIRST: () => LocalizedString
	/**
	 * Your code, frame by frame. Step forward. Step back.
	 */
	HOME_LANDING_TITLE: () => LocalizedString
	/**
	 * A LeetCode-style playground where your solution becomes a visual execution trace for trees, graphs, grids, linked structures, and nested maps. JavaScript and Python in the browser, replayable state changes, and optional timing stats for JS.
	 */
	HOME_LANDING_SUBTITLE: () => LocalizedString
	/**
	 * Frequently asked questions
	 */
	HOME_HERO_FAQ_LINK: () => LocalizedString
	/**
	 *  →
	 */
	HOME_HERO_FAQ_LINK_SUFFIX: () => LocalizedString
	/**
	 * JavaScript
	 */
	HOME_LANDING_PREVIEW_CODE_LANGUAGE: () => LocalizedString
	/**
	 * solution.js
	 */
	HOME_LANDING_PREVIEW_CODE_FILENAME: () => LocalizedString
	/**
	 * Step {step} / {total}
	 */
	HOME_PREVIEW_STEP_PROGRESS: (arg: { step: number, total: number }) => LocalizedString
	/**
	 * Play
	 */
	HOME_LANDING_PREVIEW_PLAY: () => LocalizedString
	/**
	 * Pause
	 */
	HOME_LANDING_PREVIEW_PAUSE: () => LocalizedString
	/**
	 * Step back
	 */
	HOME_PREVIEW_STEP_BACK: () => LocalizedString
	/**
	 * Step forward
	 */
	HOME_PREVIEW_STEP_FORWARD: () => LocalizedString
	/**
	 * Landing preview failed to load.
	 */
	HOME_LANDING_PREVIEW_LOAD_FAILED: () => LocalizedString
	/**
	 * Unexpected landing preview initialization error.
	 */
	HOME_LANDING_PREVIEW_ERROR_UNEXPECTED: () => LocalizedString
	/**
	 * invert binary tree
	 */
	HOME_DEMO_SLUG_INVERT_BINARY_TREE: () => LocalizedString
	/**
	 * find if path exists in graph
	 */
	HOME_DEMO_SLUG_PATH_IN_GRAPH: () => LocalizedString
	/**
	 * shortest path in binary matrix
	 */
	HOME_DEMO_SLUG_SHORTEST_PATH_MATRIX: () => LocalizedString
	/**
	 * trie
	 */
	HOME_DEMO_SLUG_TRIE_NAME: () => LocalizedString
	/**
	 * Daily Problem
	 */
	DAILY_PROBLEM_FALLBACK_TITLE: () => LocalizedString
	/**
	 * 📅 Question Of Today
	 */
	DAILY_PROBLEM_SECTION_CAPTION: () => LocalizedString
	/**
	 * Question Of Today
	 */
	QUESTION_OF_TODAY_LABEL: () => LocalizedString
	/**
	 * No projects found for "{query}"
	 */
	NO_PROJECTS_FOUND_FOR_SEARCH: (arg: { query: string }) => LocalizedString
	/**
	 * How it works
	 */
	HOME_SECTION_HOW_IT_WORKS: () => LocalizedString
	/**
	 * Write your solution
	 */
	HOME_HOW_STEP_1_TITLE: () => LocalizedString
	/**
	 * Use the built-in editor with familiar patterns for each project category.
	 */
	HOME_HOW_STEP_1_BODY: () => LocalizedString
	/**
	 * Run and record
	 */
	HOME_HOW_STEP_2_TITLE: () => LocalizedString
	/**
	 * Tracked APIs turn structural work into a callstack of frames—no canned animation.
	 */
	HOME_HOW_STEP_2_BODY: () => LocalizedString
	/**
	 * Scrub the timeline
	 */
	HOME_HOW_STEP_3_TITLE: () => LocalizedString
	/**
	 * Step forward and backward, change speed, and inspect each operation in the log.
	 */
	HOME_HOW_STEP_3_BODY: () => LocalizedString
	/**
	 * Capabilities
	 */
	HOME_SECTION_WHY_DSTUCT: () => LocalizedString
	/**
	 * See the algorithm, not just output
	 */
	HOME_PILLAR_VIS_TITLE: () => LocalizedString
	/**
	 * Replay how your data structures change. Understand and debug with a real execution trace.
	 */
	HOME_PILLAR_VIS_BODY: () => LocalizedString
	/**
	 * Smooth UI while code runs
	 */
	HOME_PILLAR_WORKERS_TITLE: () => LocalizedString
	/**
	 * JavaScript runs in a Web Worker; Python uses Pyodide in its own worker so the page stays responsive.
	 */
	HOME_PILLAR_WORKERS_BODY: () => LocalizedString
	/**
	 * Time-travel playback
	 */
	HOME_PILLAR_REPLAY_TITLE: () => LocalizedString
	/**
	 * Play, pause, step, replay, and tune playback speed—including keyboard shortcuts.
	 */
	HOME_PILLAR_REPLAY_BODY: () => LocalizedString
	/**
	 * Benchmark JavaScript
	 */
	HOME_PILLAR_BENCH_TITLE: () => LocalizedString
	/**
	 * Measure many runs with median, percentiles, and a chart. Benchmark mode is JS-only today.
	 */
	HOME_PILLAR_BENCH_BODY: () => LocalizedString
	/**
	 * Two languages, one playground
	 */
	HOME_SECTION_LANGUAGES: () => LocalizedString
	/**
	 * JavaScript
	 */
	HOME_LANG_JS_TITLE: () => LocalizedString
	/**
	 * Runs locally in a worker—no round-trip for visualization. Full benchmark support.
	 */
	HOME_LANG_JS_BODY: () => LocalizedString
	/**
	 * Python
	 */
	HOME_LANG_PYTHON_TITLE: () => LocalizedString
	/**
	 * Real CPython via Pyodide in the browser—no install needed. Preloads when you open a Python solution; first visit downloads the runtime (cached afterward). Standard library only.
	 */
	HOME_LANG_PYTHON_BODY: () => LocalizedString
	/**
	 * Algorithm gallery
	 */
	HOME_SECTION_TRY_DEMOS: () => LocalizedString
	/**
	 * Open a curated playground to see the debugger on a real problem, or jump into the full browser.
	 */
	HOME_TRY_DEMOS_LEAD: () => LocalizedString
	/**
	 * Binary tree
	 */
	HOME_DEMO_TREE: () => LocalizedString
	/**
	 * Graph path
	 */
	HOME_DEMO_GRAPH: () => LocalizedString
	/**
	 * Grid BFS
	 */
	HOME_DEMO_GRID: () => LocalizedString
	/**
	 * Trie / map
	 */
	HOME_DEMO_TRIE: () => LocalizedString
	/**
	 * Common questions
	 */
	HOME_SECTION_FAQ: () => LocalizedString
	/**
	 * Save progress in the cloud
	 */
	HOME_AUTH_HEADLINE_SIGNED_OUT: () => LocalizedString
	/**
	 * Sign in to keep projects, test cases, and solutions synced. Explore public examples without an account.
	 */
	HOME_AUTH_BODY_SIGNED_OUT: () => LocalizedString
	/**
	 * Your runs execute in the browser; signing in is for saving and social features.
	 */
	HOME_AUTH_VISUALIZATION_NOTE: () => LocalizedString
	/**
	 * Open profile
	 */
	HOME_OPEN_PROFILE: () => LocalizedString
	/**
	 * We couldn’t build your profile link. Open your profile from the account menu in the header.
	 */
	HOME_PROFILE_LINK_UNAVAILABLE: () => LocalizedString
	/**
	 * We couldn’t load the daily problem. Please try again later.
	 */
	HOME_DAILY_QUESTION_ERROR: () => LocalizedString
	/**
	 * Not sure what to solve?
	 */
	HOME_DAILY_SECTION_TITLE: () => LocalizedString
	/**
	 * Here is a daily problem from LeetCode—open it in the playground when you are ready.
	 */
	HOME_DAILY_SECTION_LEAD: () => LocalizedString
	/**
	 * Why is there no visualization after I run?
	 */
	HOME_FAQ_Q_01: () => LocalizedString
	/**
	 * Visual playback comes from dStruct's tracked data-structure APIs. Pick a matching project category and use the wrappers the playground expects. Plain objects without those APIs may print output but won't produce a step-by-step replay.
	 */
	HOME_FAQ_A_01: () => LocalizedString
	/**
	 * What problems and structures are supported?
	 */
	HOME_FAQ_Q_02: () => LocalizedString
	/**
	 * Trees, BST, linked lists, graphs, grids and matrices, arrays, heaps, stacks, trie, DP, two pointers, sliding window, backtracking, and more. Browse the playground or check categories when creating a project.
	 */
	HOME_FAQ_A_02: () => LocalizedString
	/**
	 * Do I need to install Python?
	 */
	HOME_FAQ_Q_03: () => LocalizedString
	/**
	 * No for normal use. JavaScript runs in a Web Worker; Python runs with Pyodide in the browser. A local Python server is optional for developers only.
	 */
	HOME_FAQ_A_03: () => LocalizedString
	/**
	 * Does my code run on your servers?
	 */
	HOME_FAQ_Q_04: () => LocalizedString
	/**
	 * By default, no—execution happens in your browser. Saving projects, sign-in, and browsing cloud projects use the backend like any web app.
	 */
	HOME_FAQ_A_04: () => LocalizedString
	/**
	 * Can I use JavaScript and Python?
	 */
	HOME_FAQ_Q_05: () => LocalizedString
	/**
	 * Yes. Projects can store separate JS and Python solutions. Benchmark mode is JavaScript-only today.
	 */
	HOME_FAQ_A_05: () => LocalizedString
	/**
	 * Why does Python show a loading bar?
	 */
	HOME_FAQ_Q_06: () => LocalizedString
	/**
	 * Pyodide preloads in the background when you open a Python page. The first visit downloads the runtime (~30 MB, then cached); WASM startup can take a few seconds even from cache. After that, Run is usually quick.
	 */
	HOME_FAQ_A_06: () => LocalizedString
	/**
	 * Can I use NumPy or pip packages?
	 */
	HOME_FAQ_Q_07: () => LocalizedString
	/**
	 * Not in the default playground—standard library only. Third-party imports will fail.
	 */
	HOME_FAQ_A_07: () => LocalizedString
	/**
	 * How long can a run take?
	 */
	HOME_FAQ_Q_08: () => LocalizedString
	/**
	 * Python times out after 30 seconds by default; the worker is then recreated. Cancellation is coarse for very heavy work.
	 */
	HOME_FAQ_A_08: () => LocalizedString
	/**
	 * How do I save my work?
	 */
	HOME_FAQ_Q_09: () => LocalizedString
	/**
	 * Use public projects and the editor without signing in. To persist projects, test cases, and named solutions, sign in.
	 */
	HOME_FAQ_A_09: () => LocalizedString
	/**
	 * Can I share projects or learn from others?
	 */
	HOME_FAQ_Q_10: () => LocalizedString
	/**
	 * Yes. Make a project public and use Browse to discover examples.
	 */
	HOME_FAQ_A_10: () => LocalizedString
	/**
	 * What does linking my LeetCode account do?
	 */
	HOME_FAQ_Q_11: () => LocalizedString
	/**
	 * Optional profile features, pasting a LeetCode problem URL to fill metadata, and shortcuts to open the same problem on LeetCode. Submitting solutions still happens on LeetCode—dStruct is a companion playground.
	 */
	HOME_FAQ_A_11: () => LocalizedString
	/**
	 * Can I measure how fast my solution is?
	 */
	HOME_FAQ_Q_12: () => LocalizedString
	/**
	 * Yes, for JavaScript—use Benchmark mode (many iterations, median, percentiles, chart). Python does not have benchmark mode yet.
	 */
	HOME_FAQ_A_12: () => LocalizedString
	/**
	 * Does dStruct work on a phone or tablet?
	 */
	HOME_FAQ_Q_13: () => LocalizedString
	/**
	 * There is a mobile-friendly playground flow with keep-alive when switching tabs. Long editing sessions are still easiest on desktop.
	 */
	HOME_FAQ_A_13: () => LocalizedString
	/**
	 * Is dStruct open source?
	 */
	HOME_FAQ_Q_14: () => LocalizedString
	/**
	 * Yes. See the LICENSE file in the repository (AGPL-3.0).
	 */
	HOME_FAQ_A_14: () => LocalizedString
}

export type Formatters = {
	weekday: (value: Date) => unknown
}
